import typing

Event = typing.NewType("Event", int)

BEFORE_MINIBATCH = Event(1)
AFTER_MINIBATCH = Event(2)

BEFORE_TRAIN_MINIBATCH = Event(3)
AFTER_TRAIN_MINIBATCH = Event(4)

BEFORE_EVAL_MINIBATCH = Event(5)
AFTER_EVAL_MINIBATCH = Event(6)

BEFORE_TEST_MINIBATCH = Event(7)
AFTER_TEST_MINIBATCH = Event(8)

BEFORE_TRAIN = Event(9)
AFTER_TRAIN = Event(10)

BEFORE_EVAL = Event(11)
AFTER_EVAL = Event(12)

BEFORE_TEST = Event(13)
AFTER_TEST = Event(14)

BEFORE_EPOCH = Event(15)
AFTER_EPOCH = Event(16)
