import typing

Event = typing.NewType('Event', int)

BEFORE_MINIBATCH = Event(1)
AFTER_MINIBATCH = Event(2)

BEFORE_TRAIN_MINIBATCH = Event(3)
AFTER_TRAIN_MINIBATCH = Event(4)

BEFORE_EVAL_MINIBATCH = Event(5)
AFTER_EVAL_MINIBATCH = Event(6)

BEFORE_TRAIN = Event(7)
AFTER_TRAIN = Event(8)

BEFORE_EVAL = Event(9)
AFTER_EVAL = Event(10)

BEFORE_EPOCH = Event(11)
AFTER_EPOCH = Event(12)
