language: python

python:
    - "3.6"

install:
    - pip install mypy
    - pip install codecov
    - pip install pytest-cov
    - python setup.py install

env:
    global:
        - SOURCE_FILES=`find ./torchfuel/ -name '*.py'`

script:
    - mypy $SOURCE_FILES --ignore-missing-imports
    - pytest tests/ --cov=torchfuel

notifications:
    email:
        on_success: never
        on_failure: never

after_success:
  - codecov
