language: python

python:
    - "3.6"

install:
    - pip install codecov pytest-cov
    - python setup.py install

script:
    - pytest test/ --cov=torchfuel

notifications:
    email:
        on_success: never
        on_failure: never

after_success:
  - codecov
